### ISSUE TITLE
Bug: ParameterOptimizationServer.tmpl.cpp  

### ISSUE THREAD

**Issue by Yufeng-shen** [FrankieLi/IceNine#4]
line 193:  RUNTIME_ASSERT( nCommand == XDMParallel::REPORT_MC, "\nDriver::Server: Unknown command from client recv \n" );
should be:  RUNTIME_ASSERT( nCommand == XDMParallel::REPORT_MC_LIST, "\nDriver::Server: Unknown command from client recv \n" );

**Comment by FrankieLi** [comment]
Thanks. Will create an update.
